"""Import the delivered GLB into a NEW Blender scene and optionally export a roundtrip GLB.

Example:
blender --background --factory-startup --python scripts/blender_roundtrip.py -- --export-glb

Requires Blender with glTF import/export enabled. Does not control a running Blender UI.
The supplied campus.glb is generated by this project's Three.js geometry script, not Blender.
"""
import argparse
from pathlib import Path
import sys
import json

import bpy


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--export-glb', action='store_true')
    args = parser.parse_args(sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else [])
    root = Path(__file__).resolve().parent.parent
    source = root / 'public' / 'models' / 'campus.glb'
    if not source.is_file():
        raise FileNotFoundError(f'Run npm run model first: {source}')
    # A separate scene leaves any existing scene data intact.
    scene = bpy.data.scenes.new('Yangzijin_Campus_Imported')
    bpy.context.window.scene = scene
    scene.unit_settings.system = 'METRIC'
    bpy.ops.import_scene.gltf(filepath=str(source))
    ids = {str(obj.get('buildingId')) for obj in scene.objects if obj.get('buildingId')}
    data = json.loads((root / 'src' / 'data' / 'campus.json').read_text(encoding='utf-8'))
    expected = {item['buildingId'] for item in data['layout']['buildings']}
    if not expected.issubset(ids):
        raise RuntimeError(f'Missing building IDs: {expected - ids}')
    output = root / 'blender'
    output.mkdir(exist_ok=True)
    bpy.ops.wm.save_as_mainfile(filepath=str(output / 'campus.blend'))
    if args.export_glb:
        bpy.ops.export_scene.gltf(
            filepath=str(output / 'campus.roundtrip.glb'),
            export_format='GLB', export_extras=True, use_active_scene=True,
        )
    print('Saved campus.blend. Verified building IDs:', len(ids))


if __name__ == '__main__':
    main()
